image: openjdk:13

stages:
  - build
  - test

build:
  stage: build
  script: ./mvnw compile

test:
  stage: test
  script: ./mvnw test
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
