spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:hr
  flyway:
    enabled: false
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: always
  mail:
    host: smtp.mailgun.org
    username: hr@sandbox249b417c04164b2cb3206546eab97c38.mailgun.org
    password: 527cf58d85c6875ffaf6e53981f04ba8-fd0269a6-ff037e7a
    port: 25
management:
  health:
    ldap:
      enabled: false
logging:
  level:
    org:
      springframework:
        security: info
