spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:hr;DB_CLOSE_ON_EXIT=FALSE
  flyway:
    enabled: false
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: always
  mail:
    host: smtp.sendgrid.net
    username: apikey
    password: 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
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: true
  jackson:
    mapper:
      default-view-inclusion: true
  ldap:
    embedded:
      port: 8389
      ldif: "classpath:users.ldif"
      base-dn: "dc=hr,dc=com"
    urls: "ldap://localhost:8389/dc=hr,dc=com"
management:
  health:
    ldap:
      enabled: false
logging:
  level:
    org:
      springframework:
        security: info
storage:
  location: /home/matt/hr
